const jobs = [
    {
        id: 'frontend-engineer',
        title: 'Frontend Engineer',
        location: 'Remote (Canada)',
        type: 'Full-time',
        summary: 'Build UI components and pages using Next.js and Mantine.',
        responsibilities: [
            'Build and maintain React/Next.js features',
            'Collaborate with designers to implement UI',
            'Write unit and integration tests for components',
        ],
        qualifications: [
            '3+ years React experience',
            'Familiarity with Next.js App Router',
            'TypeScript and testing experience',
        ],
        posted: '2025-12-07',
    },
    {
        id: 'fullstack-engineer',
        title: 'Fullstack Engineer',
        location: 'Hybrid - Toronto, ON',
        type: 'Full-time',
        summary: 'Work across frontend and backend to deliver product features.',
        responsibilities: [
            'Design and implement APIs',
            'Work on frontend pages and server components',
            'Improve CI and deployment workflows',
        ],
        qualifications: [
            'Experience with Next.js and Node.js',
            'Comfortable with GraphQL and REST',
            'Strong TypeScript skills',
        ],
        posted: '2025-12-07',
    },
    {
        id: 'backend-engineer',
        title: 'Backend Engineer',
        location: 'Remote (US/Canada)',
        type: 'Full-time',
        summary: 'Design and maintain scalable backend services and APIs.',
        responsibilities: [
            'Build robust REST and GraphQL APIs',
            'Design database schemas and optimize queries',
            'Implement authentication and authorization systems',
            'Work on microservices architecture',
        ],
        qualifications: [
            '4+ years backend development experience',
            'Proficiency in Node.js or similar',
            'Experience with databases (PostgreSQL, MongoDB)',
            'Understanding of system design principles',
        ],
        posted: '2025-12-05',
    },
    {
        id: 'product-manager',
        title: 'Product Manager',
        location: 'Toronto, ON',
        type: 'Full-time',
        summary: 'Lead product strategy and roadmap for our core platforms.',
        responsibilities: [
            'Define product vision and strategy',
            'Collaborate with engineering and design teams',
            'Conduct user research and gather feedback',
            'Prioritize features and manage product backlog',
        ],
        qualifications: [
            '3+ years product management experience',
            'Experience in SaaS or consulting tech',
            'Strong communication and analytical skills',
            'Familiarity with agile development',
        ],
        posted: '2025-12-06',
    },
    {
        id: 'devops-engineer',
        title: 'DevOps Engineer',
        location: 'Hybrid - Toronto, ON',
        type: 'Contract',
        summary: 'Manage infrastructure, CI/CD pipelines, and deployment processes.',
        responsibilities: [
            'Set up and maintain cloud infrastructure (AWS/GCP)',
            'Implement and optimize CI/CD pipelines',
            'Monitor system performance and troubleshoot issues',
            'Implement security best practices',
        ],
        qualifications: [
            '3+ years DevOps experience',
            'Strong knowledge of Docker and Kubernetes',
            'Experience with AWS or GCP',
            'Scripting skills (Bash, Python, Go)',
        ],
        posted: '2025-12-04',
    },
    {
        id: 'ui-designer',
        title: 'UI/UX Designer',
        location: 'Remote (Canada)',
        type: 'Full-time',
        summary: 'Create intuitive and visually appealing user interfaces.',
        responsibilities: [
            'Design user interfaces for web and mobile applications',
            'Conduct user research and usability testing',
            'Create prototypes and design specifications',
            'Work closely with engineering teams on implementation',
        ],
        qualifications: [
            '3+ years UI/UX design experience',
            'Proficiency in Figma or similar design tools',
            'Portfolio showcasing design work',
            'Understanding of responsive design principles',
        ],
        posted: '2025-12-07',
    },
    {
        id: 'qa-engineer',
        title: 'QA Engineer',
        location: 'Remote (US/Canada)',
        type: 'Full-time',
        summary: 'Ensure quality through comprehensive testing and automation.',
        responsibilities: [
            'Develop and execute test cases and test plans',
            'Implement automated testing frameworks',
            'Identify and document bugs and issues',
            'Collaborate with developers on quality improvements',
        ],
        qualifications: [
            '2+ years QA testing experience',
            'Experience with automated testing tools',
            'Strong attention to detail',
            'Understanding of web application technologies',
        ],
        posted: '2025-12-03',
    },
    {
        id: 'data-analyst',
        title: 'Data Analyst',
        location: 'Hybrid - Toronto, ON',
        type: 'Full-time',
        summary: 'Transform data into actionable insights to drive business decisions.',
        responsibilities: [
            'Analyze large datasets and identify patterns',
            'Create dashboards and reports for stakeholders',
            'Design and implement data collection processes',
            'Provide data-driven recommendations',
        ],
        qualifications: [
            '2+ years data analysis experience',
            'Proficiency in SQL and Python',
            'Experience with data visualization tools (Tableau, Power BI)',
            'Strong statistical knowledge',
        ],
        posted: '2025-12-02',
    },
];

export default jobs;
